version: '3.3'

services:
  tf2-sourcemod: 
    image: cm2network/tf2:sourcemod
    container_name: "tf2-sourcemod"
    network_mode: "host"

    volumes:
      - ./tf2-sourcemod-data:/home/steam/tf-dedicated

    environment:
      SRCDS_TOKEN: "CHANGEME"
      SRCDS_WORKSHOP_AUTHKEY: "CHANGEME"
      SRCDS_RCONPW: "CHANGEME"
      SRCDS_PORT: 27015
      SRCDS_MAXPLAYERS: 18
      SRCDS_HOSTNAME: "TF2 Sourcemod"